// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: UserSettings.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.personalnotesapp.data.model.proto;

