// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: UserSettings.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.personalnotesapp.data.model.proto;

@kotlin.jvm.JvmName("-initializeuserSettings")
public inline fun userSettings(block: com.example.personalnotesapp.data.model.proto.UserSettingsKt.Dsl.() -> kotlin.Unit): com.example.personalnotesapp.data.model.proto.UserSettings =
  com.example.personalnotesapp.data.model.proto.UserSettingsKt.Dsl._create(com.example.personalnotesapp.data.model.proto.UserSettings.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `UserSettings`
 */
public object UserSettingsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.personalnotesapp.data.model.proto.UserSettings.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.personalnotesapp.data.model.proto.UserSettings.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.personalnotesapp.data.model.proto.UserSettings = _builder.build()

    /**
     * `bool isDarkMode = 1;`
     */
    public var isDarkMode: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsDarkMode")
        get() = _builder.isDarkMode
      @kotlin.jvm.JvmName("setIsDarkMode")
        set(value) {
        _builder.isDarkMode = value
      }
    /**
     * `bool isDarkMode = 1;`
     */
    public fun clearIsDarkMode() {
      _builder.clearIsDarkMode()
    }

    /**
     * `int32 fontSize = 2;`
     */
    public var fontSize: kotlin.Int
      @kotlin.jvm.JvmName("getFontSize")
        get() = _builder.fontSize
      @kotlin.jvm.JvmName("setFontSize")
        set(value) {
        _builder.fontSize = value
      }
    /**
     * `int32 fontSize = 2;`
     */
    public fun clearFontSize() {
      _builder.clearFontSize()
    }

    /**
     * `bool autoSave = 3;`
     */
    public var autoSave: kotlin.Boolean
      @kotlin.jvm.JvmName("getAutoSave")
        get() = _builder.autoSave
      @kotlin.jvm.JvmName("setAutoSave")
        set(value) {
        _builder.autoSave = value
      }
    /**
     * `bool autoSave = 3;`
     */
    public fun clearAutoSave() {
      _builder.clearAutoSave()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.personalnotesapp.data.model.proto.UserSettings.copy(block: `com.example.personalnotesapp.data.model.proto`.UserSettingsKt.Dsl.() -> kotlin.Unit): com.example.personalnotesapp.data.model.proto.UserSettings =
  `com.example.personalnotesapp.data.model.proto`.UserSettingsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

