// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: UserSettings.proto
// Protobuf Java Version: 4.32.0

package com.example.personalnotesapp.data.model.proto;

/**
 * Protobuf type {@code UserSettings}
 */
@com.google.protobuf.Generated
public final class UserSettings extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:UserSettings)
    UserSettingsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      UserSettings.class.getName());
  }
  // Use UserSettings.newBuilder() to construct.
  private UserSettings(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UserSettings() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.personalnotesapp.data.model.proto.UserSettingsOuterClass.internal_static_UserSettings_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.personalnotesapp.data.model.proto.UserSettingsOuterClass.internal_static_UserSettings_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.personalnotesapp.data.model.proto.UserSettings.class, com.example.personalnotesapp.data.model.proto.UserSettings.Builder.class);
  }

  public static final int ISDARKMODE_FIELD_NUMBER = 1;
  private boolean isDarkMode_ = false;
  /**
   * <code>bool isDarkMode = 1;</code>
   * @return The isDarkMode.
   */
  @java.lang.Override
  public boolean getIsDarkMode() {
    return isDarkMode_;
  }

  public static final int FONTSIZE_FIELD_NUMBER = 2;
  private int fontSize_ = 0;
  /**
   * <code>int32 fontSize = 2;</code>
   * @return The fontSize.
   */
  @java.lang.Override
  public int getFontSize() {
    return fontSize_;
  }

  public static final int AUTOSAVE_FIELD_NUMBER = 3;
  private boolean autoSave_ = false;
  /**
   * <code>bool autoSave = 3;</code>
   * @return The autoSave.
   */
  @java.lang.Override
  public boolean getAutoSave() {
    return autoSave_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isDarkMode_ != false) {
      output.writeBool(1, isDarkMode_);
    }
    if (fontSize_ != 0) {
      output.writeInt32(2, fontSize_);
    }
    if (autoSave_ != false) {
      output.writeBool(3, autoSave_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isDarkMode_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isDarkMode_);
    }
    if (fontSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, fontSize_);
    }
    if (autoSave_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, autoSave_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.personalnotesapp.data.model.proto.UserSettings)) {
      return super.equals(obj);
    }
    com.example.personalnotesapp.data.model.proto.UserSettings other = (com.example.personalnotesapp.data.model.proto.UserSettings) obj;

    if (getIsDarkMode()
        != other.getIsDarkMode()) return false;
    if (getFontSize()
        != other.getFontSize()) return false;
    if (getAutoSave()
        != other.getAutoSave()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISDARKMODE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDarkMode());
    hash = (37 * hash) + FONTSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getFontSize();
    hash = (37 * hash) + AUTOSAVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAutoSave());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.personalnotesapp.data.model.proto.UserSettings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.personalnotesapp.data.model.proto.UserSettings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.personalnotesapp.data.model.proto.UserSettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.personalnotesapp.data.model.proto.UserSettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.personalnotesapp.data.model.proto.UserSettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.personalnotesapp.data.model.proto.UserSettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.personalnotesapp.data.model.proto.UserSettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.personalnotesapp.data.model.proto.UserSettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.personalnotesapp.data.model.proto.UserSettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.personalnotesapp.data.model.proto.UserSettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.personalnotesapp.data.model.proto.UserSettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.personalnotesapp.data.model.proto.UserSettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.personalnotesapp.data.model.proto.UserSettings prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserSettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserSettings)
      com.example.personalnotesapp.data.model.proto.UserSettingsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.personalnotesapp.data.model.proto.UserSettingsOuterClass.internal_static_UserSettings_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.personalnotesapp.data.model.proto.UserSettingsOuterClass.internal_static_UserSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.personalnotesapp.data.model.proto.UserSettings.class, com.example.personalnotesapp.data.model.proto.UserSettings.Builder.class);
    }

    // Construct using com.example.personalnotesapp.data.model.proto.UserSettings.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isDarkMode_ = false;
      fontSize_ = 0;
      autoSave_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.personalnotesapp.data.model.proto.UserSettingsOuterClass.internal_static_UserSettings_descriptor;
    }

    @java.lang.Override
    public com.example.personalnotesapp.data.model.proto.UserSettings getDefaultInstanceForType() {
      return com.example.personalnotesapp.data.model.proto.UserSettings.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.personalnotesapp.data.model.proto.UserSettings build() {
      com.example.personalnotesapp.data.model.proto.UserSettings result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.personalnotesapp.data.model.proto.UserSettings buildPartial() {
      com.example.personalnotesapp.data.model.proto.UserSettings result = new com.example.personalnotesapp.data.model.proto.UserSettings(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.personalnotesapp.data.model.proto.UserSettings result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isDarkMode_ = isDarkMode_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fontSize_ = fontSize_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.autoSave_ = autoSave_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.personalnotesapp.data.model.proto.UserSettings) {
        return mergeFrom((com.example.personalnotesapp.data.model.proto.UserSettings)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.personalnotesapp.data.model.proto.UserSettings other) {
      if (other == com.example.personalnotesapp.data.model.proto.UserSettings.getDefaultInstance()) return this;
      if (other.getIsDarkMode() != false) {
        setIsDarkMode(other.getIsDarkMode());
      }
      if (other.getFontSize() != 0) {
        setFontSize(other.getFontSize());
      }
      if (other.getAutoSave() != false) {
        setAutoSave(other.getAutoSave());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isDarkMode_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              fontSize_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              autoSave_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isDarkMode_ ;
    /**
     * <code>bool isDarkMode = 1;</code>
     * @return The isDarkMode.
     */
    @java.lang.Override
    public boolean getIsDarkMode() {
      return isDarkMode_;
    }
    /**
     * <code>bool isDarkMode = 1;</code>
     * @param value The isDarkMode to set.
     * @return This builder for chaining.
     */
    public Builder setIsDarkMode(boolean value) {

      isDarkMode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool isDarkMode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDarkMode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isDarkMode_ = false;
      onChanged();
      return this;
    }

    private int fontSize_ ;
    /**
     * <code>int32 fontSize = 2;</code>
     * @return The fontSize.
     */
    @java.lang.Override
    public int getFontSize() {
      return fontSize_;
    }
    /**
     * <code>int32 fontSize = 2;</code>
     * @param value The fontSize to set.
     * @return This builder for chaining.
     */
    public Builder setFontSize(int value) {

      fontSize_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 fontSize = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFontSize() {
      bitField0_ = (bitField0_ & ~0x00000002);
      fontSize_ = 0;
      onChanged();
      return this;
    }

    private boolean autoSave_ ;
    /**
     * <code>bool autoSave = 3;</code>
     * @return The autoSave.
     */
    @java.lang.Override
    public boolean getAutoSave() {
      return autoSave_;
    }
    /**
     * <code>bool autoSave = 3;</code>
     * @param value The autoSave to set.
     * @return This builder for chaining.
     */
    public Builder setAutoSave(boolean value) {

      autoSave_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool autoSave = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAutoSave() {
      bitField0_ = (bitField0_ & ~0x00000004);
      autoSave_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:UserSettings)
  }

  // @@protoc_insertion_point(class_scope:UserSettings)
  private static final com.example.personalnotesapp.data.model.proto.UserSettings DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.personalnotesapp.data.model.proto.UserSettings();
  }

  public static com.example.personalnotesapp.data.model.proto.UserSettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserSettings>
      PARSER = new com.google.protobuf.AbstractParser<UserSettings>() {
    @java.lang.Override
    public UserSettings parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserSettings> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserSettings> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.personalnotesapp.data.model.proto.UserSettings getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

