// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: UserSettings.proto
// Protobuf Java Version: 4.32.0

package com.example.personalnotesapp.data.model.proto;

@com.google.protobuf.Generated
public interface UserSettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserSettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isDarkMode = 1;</code>
   * @return The isDarkMode.
   */
  boolean getIsDarkMode();

  /**
   * <code>int32 fontSize = 2;</code>
   * @return The fontSize.
   */
  int getFontSize();

  /**
   * <code>bool autoSave = 3;</code>
   * @return The autoSave.
   */
  boolean getAutoSave();
}
